PhotoAlbum/Controllers/CMS_PageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CMSWebsite.Models;

namespace CMSWebsite.Controllers
{
    public class CMS_PageController : CMS_BaseController
    {
        // GET: CMS_Page
        public ActionResult Index()
        {
            return View();
        }

        #region [Tất cả trang tĩnh]

        public ActionResult AllPage()
        {
            InitView();
            List<PostView> model = new List<PostView>();
            try
            {
                List<Web_Post> lstPost = new List<Web_Post>();
                lstPost = dbCMS.Web_Post.Where(o => o.Active == true && o.PostType == "page").OrderByDescending(o => o.PostCreateDate).ToList();
                List<Web_PostCategory> arr = new List<Web_PostCategory>();
                PostView temp;
                int authorID = 0;
                for (int i = 0; i < lstPost.Count; i++)
                {
                    temp = new PostView();
                    authorID = lstPost[i].PostAuthor.Value;
                    temp.PostAuthor = dbCMS.CMS_Users.Where(o => o.UserID == authorID).Select(o => o.FullName).FirstOrDefault();

                    temp.PostDate = Convert.ToDateTime(lstPost[i].PostCreateDate).ToString("dd/MM/yyyy lúc HH:mm");
                    
                    temp.UrlFriendly = lstPost[i].URLFriendly;
                    temp.PostId = lstPost[i].PostId;
                    temp.PostTitle = lstPost[i].PostTitle;
                    temp.PostCate = "";
                    model.Add(temp);
                }
            }
            catch (Exception ex)
            {

            }
            return PartialView("AllPage", model);
        }

        #endregion

        #region [Thêm mới trang tĩnh]

        public ActionResult NewPage()
        {
            InitView();

            return View();
        }

        // Thêm mới bài viết 
        [HttpPost]
        public ActionResult AddPage(PostModel models)
        {
            InitView();
            try
            {
                Web_Post newPage = new Web_Post();
                // int id = Convert.ToInt32(Session["TMDTUserID"]);
                newPage.PostAuthor = this.UserID;
                newPage.PostContent = models.contentPost;
                newPage.PostCreateDate = DateTime.Now;
                newPage.PostFaceImage = "";
                newPage.PostSeoDesc = models.seoDescPost;
                newPage.PostType = "page";
                newPage.PostSeoKeyword = models.seoKeywordPost;
                newPage.PostTitle = models.titlePost;
                newPage.Active = true;
                newPage.URLFriendly = "";
                newPage.PostDescription = "";
                newPage.URLFriendly = "trang/" + ToFriendlyUrl(models.titlePost);
                dbCMS.Web_Post.Add(newPage);
                dbCMS.SaveChanges();
               
                dbCMS.SaveChanges();
                WriteLogToDB(this.UserID, this.Fullname, "Thêm mới trang", this.Fullname + " tạo trang : " + newPage.PostTitle, DateTime.Now);
                return Content("OK");
            }
            catch (Exception)
            {
                return Content("Error");
            }
        }

        // Xóa trang
        public ActionResult DeletePage(int pageID)
        {
            InitView();
            try
            {
                Web_Post delete = dbCMS.Web_Post.Where(o => o.PostId == pageID).FirstOrDefault();
                delete.Active = false;
                dbCMS.SaveChanges();
                WriteLogToDB(this.UserID, this.Fullname, "Xóa trang ", this.Fullname + " xóa trang : " + delete.PostTitle, DateTime.Now);
                return Content("Success");
            }
            catch (Exception)
            {
                return Content("Error");
            }
        }

        // Sửa trang
        public ActionResult ViewEdit(int id)
        {
            InitView();
            EditPostModel model = new EditPostModel();
            model.PostEdit = dbCMS.Web_Post.Where(o => o.PostId == id && o.Active == true).FirstOrDefault();
            return View(model);
        }

        [HttpPost]
        public ActionResult EditPage(PostModel models)
        {
            InitView();
            try
            {
                int pid = Convert.ToInt32(models.postId);
                Web_Post newPost = dbCMS.Web_Post.Where(o => o.PostId == pid).FirstOrDefault();
                newPost.PostContent = models.contentPost;
                newPost.PostUpdateDate = DateTime.Now;
                newPost.PostSeoDesc = models.seoDescPost;
                newPost.PostSeoKeyword = models.seoKeywordPost;
                newPost.PostTitle = models.titlePost;
                newPost.URLFriendly = "trang/" + ToFriendlyUrl(models.titlePost);
                dbCMS.SaveChanges();
               
                WriteLogToDB(this.UserID, this.Fullname, "Sửa trang", this.Fullname + " sửa nội dung trang : " + newPost.PostTitle, DateTime.Now);
                return Content("OK");
            }
            catch (Exception)
            {
                return Content("Error");
            }
        }


        #endregion

    }
}

PhotoAlbum/Views/CMS_Page/AllPage.cshtml
@model List<CMSWebsite.Models.PostView>

@{
    ViewBag.Title = "Tất cả trang tĩnh";
    Layout = "~/Views/Shared/CMS_MasterPage.cshtml";
}

<div class="page-title">
    <div class="title_left">
        <h3>Tất cả trang</h3>
    </div>
    <div class="title_right">
        
    </div>
</div>
<div class="clearfix"></div>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12" id="tblShowCar">
        <table id="example1" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Tên bài viết</th>
                    <th>Đường dẫn</th>
                    <th>Ngày viết</th>
                    <th>Tác giả</th>
                    <th width="100px">Công cụ</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.Count != 0)
                {
                    foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.PostId</td>
                            <td>@item.PostTitle</td>
                            <td>@item.UrlFriendly</td>
                            <td>@item.PostDate</td>
                            <td>@item.PostAuthor</td>
                            <td width="100px">
                                <a href="#"><img src="~/Images/cms/icon/edit.png" width="25" height="25" title="Sửa bài viết" onclick="location.href='@Url.Action("ViewEdit", "CMS_Page", new { id = @item.PostId })'" /></a>&nbsp;
                                <a href="/@item.UrlFriendly" target="_blank"><img src="~/Images/cms/icon/view.png" width="25" height="25" title="Xem trang"  /></a>&nbsp;
                                <a href="#"><img src="~/Images/cms/icon/delete.png" width="25" height="25" title="Xóa bài viết" onclick="deletePost(@item.PostId)" /></a>
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>

    </div> <!-- End col-md-12  -->
</div>


<script type="text/javascript" src="~/Scripts/cms/cms.all-page.js"></script>

PhotoAlbum/Views/CMS_Page/NewPage.cshtml
@{
    ViewBag.Title = "Thêm mới trang";
    Layout = "~/Views/Shared/CMS_MasterPage.cshtml";
}

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-md-9">
            <div class="form-group" id="box-title">
                <input type="text" class="form-control" id="postTitle" placeholder="Nhập tiêu đề trang">
            </div>
            <div style="display:block">
                <textarea id="editor1" name="editor1" rows="30" cols="80"></textarea>
            </div>

            <div class="box-header with-border">
                <h5 class="box-title">Thông tin SEO</h5>
            </div><!-- /.box-header -->
            <form role="form" class="form-horizontal">
                <div class="box-body">
                    <div class="form-group">
                        <label for="inputPassword3" class="col-sm-2 control-label">SEO Keywords</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="seoKeyword" placeholder="Từ khóa">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">SEO Description</label>
                        <div class="col-sm-10">
                            <textarea class="form-control" rows="3" id="seoDesc" placeholder="Mô tả ..."></textarea>
                        </div>
                    </div>
                </div><!-- /.box-body -->
            </form>
        </div>
        <div class="col-md-3">
            <div class="box-right">
                <div class="box-header with-border">
                    <h5 class="box-title">Xuất bản</h5>
                </div><!-- /.box-header -->
                <div class="box-body">
                    <a onclick="addPage()" class="btn btn-primary pull-right">Thêm trang</a>
                    <div class="clearfix"></div>
                </div>
            </div><!-- /.box -->
        </div>
    </div>
</section><!-- /.content -->

<script type="text/javascript" src="~/Scripts/cms/cms.add-page.js"></script>

PhotoAlbum/Views/CMS_Page/ViewEdit.cshtml
@model CMSWebsite.Models.EditPostModel
@{
    ViewBag.Title = "Sửa trang ";
    Layout = "~/Views/Shared/CMS_MasterPage.cshtml";
}

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-md-9">
            <div class="form-group" id="box-title">
                <input type="text" class="form-control" id="postTitle" placeholder="Nhập tiêu đề trang" value="@Model.PostEdit.PostTitle">
            </div>
            <div style="display:block">
                <textarea id="editor1" name="editor1" rows="30" cols="80">@Model.PostEdit.PostContent</textarea>
            </div>

            <div class="box-header with-border">
                <h5 class="box-title">Thông tin SEO</h5>
            </div><!-- /.box-header -->
            <form role="form" class="form-horizontal">
                <div class="box-body">
                    <div class="form-group">
                        <label for="inputPassword3" class="col-sm-2 control-label">SEO Keywords</label>
                        <div class="col-sm-10">
                            <input type="hidden" value="@Model.PostEdit.PostId" id="editId" />
                            <input type="text" class="form-control" id="seoKeyword" placeholder="Từ khóa" value="@Model.PostEdit.PostSeoKeyword">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">SEO Description</label>
                        <div class="col-sm-10">
                            <textarea class="form-control" rows="3" id="seoDesc" placeholder="Mô tả ...">@Model.PostEdit.PostSeoDesc</textarea>
                        </div>
                    </div>
                </div><!-- /.box-body -->
            </form>
        </div>
        <div class="col-md-3">
            <div class="box-right">
                <div class="box-header with-border">
                    <h5 class="box-title">Xuất bản</h5>
                </div><!-- /.box-header -->
                <div class="box-body">
                    <a onclick="editPage()" class="btn btn-primary pull-right">Sửa trang</a>
                    <div class="clearfix"></div>
                </div>
            </div><!-- /.box -->
        </div>
    </div>
</section><!-- /.content -->

<script type="text/javascript" src="~/Scripts/cms/cms.edit-page.js"></script>